# ##### BEGIN MIT LICENSE BLOCK #####
#
# Copyright (c) 2015 - 2017 Pixar
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#
# ##### END MIT LICENSE BLOCK #####

# ######################################## #
# Common Utils: no ops, no ui pure python. #
# ##########################################

from datetime import datetime

# a more userfriendly version of util.debug()
# No config/flag to disable, always active.
def echo(msg):
    """
    Prints the 'msg' to console including autogenerated timestamp.

    Import: from [.|..]common_utils import echo
    Usage:  echo("My Insane Message.")
    Output: [2018-01-03 05:25:24] RfB: My Insane Message.

    Since this is typically a very temporary output, this can be happen
    quite often. It should be.

    Useful at the beginning or ending of a large/long/complicated operation.
    """
    t = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    m = '[{}] RfB: {}'.format(t, msg)
    print(m)
